# Generated by Django 6.0.6 on 2026-06-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Viewer', 'Viewer'), ('Creator', 'Creator')], default='Viewer', max_length=20),
        ),
    ]
