# Generated by Django 6.0.6 on 2026-06-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
