# Generated by Django 6.0.6 on 2026-06-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='user',
        ),
        migrations.AddField(
            model_name='receipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert')], default='Lunch', max_length=50),
        ),
    ]
